# Generated by Django 4.2.4 on 2023-08-21 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_ID',
            new_name='id',
        ),
    ]
