# Generated by Django 4.2.4 on 2023-08-21 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TTSAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('audio_file', models.FileField(upload_to='tts/')),
            ],
        ),
        migrations.CreateModel(
            name='TTSAudioTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_message', models.TextField()),
                ('audio_file', models.FileField(upload_to='tts_title/')),
            ],
        ),
        migrations.CreateModel(
            name='ttsPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tts_title_message', models.CharField(max_length=100)),
                ('tts_message', models.TextField()),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
